spring:
  config:
    import: optional:configserver:http://${SRV_CONFIG_HOST:127.0.0.1}:${SRV_CONFIG_PORT:8888}/
  cloud:
    config:
      name: service-discovery
  application:
    name: service-discovery
  profiles:
    active: local